# Generated by Django 2.1.3 on 2018-11-27 15:52

from django.db import migrations
from random import randrange

# Заполняем комментарии случайными пользователями

def random_users(apps, schema_editor):
    # Импортировать модели нельзя используем следующий приём
    Comments = apps.get_model('article','Comments')
    User = apps.get_model('auth','User')
    for comment in Comments.objects.all():
        rand_id = randrange(1,4)
        comment.comments_from = User.objects.get(id=rand_id)
        comment.save()

def backwards_random_users():
    # Код для отката миграции
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20181127_1849'),
    ]

    operations = [
        # Второй аргумент - функция для отката
        migrations.RunPython(random_users),
    ]
